### PR TITLE
make sure that environment variables are used correctly

### PR DESCRIPTION
**Pull request by ahussein**

### CODE REVIEW

**Comment by rkhamis** [comment]
Already fixed by https://github.com/Jumpscale/jumpscale_core8/pull/252

**Comment by ahussein** [comment]
are you sure that PR #252 fix the issue, as far as i can see, it will write the environment variables after pulling the repos ?

**Comment by rkhamis** [comment]
@ahussein nice catch

**Comment by abdulrahmantkhalifa** [comment]
reviewed and tested.
the  #252 fixes both issues

**Comment by ahussein** [comment]
@abdulrahmantkhalifa  I just tried to install js8 and tried to set the JSBRANCH env variable but the master branch was used anyhow!

**Pull request merged**
