### PR TITLE
Improving skydns and adding mail (MX and TXT) support

### PR DESCRIPTION
**Pull request by maxux**

### CODE REVIEW

**Comment by despiegk** [comment]
do we still use this?
thought we were going to go to other dns server?

**Comment by zaibon** [comment]
see https://github.com/gig-projects/org_development/issues/5#issuecomment-212278550

**Comment by despiegk** [comment]
see story, indeed, security is not an issue

**Comment by despiegk** [comment]
please merge into master so we don't loose the changes

**Pull request merged**
