### PR TITLE
Refactor Flist tools to be usable by core0 0.10.0

### PR DESCRIPTION
**Pull request by zaibon**
also add a small main method to the flist module to easily create a flist

### CODE REVIEW

**Comment by rkhamis** [comment]
Should this be in 8.1.0?
I can already hear people screaming about new imports

**Comment by zaibon** [comment]
No indeed this doesn't need to be in 8.1.0, you can report it for later.
I need a review from @maxux too

**Comment by despiegk** [comment]
same comment here, plist is being implemented differently, lets not loose too much time here

**Comment by muhamadazmy** [comment]
I think we need to have some sort of filtering on what files need to be uploaded and added in the flist. For examples, `.h` files, `man` and `doc` pages. `.pyc` files `icons`, `wallpapers`, `images`, and anything that won't be needed in a production environment.

This will reduce the flist size, and also the number of files uploaded to the store.

**Comment by rkhamis** [comment]
@maxux @zaibon I changed the base to be 8.2.0. Can you update this branch or delete it?

**Comment by maxux** [comment]
Need @zaibon confirmation, but this can be probably dropped. The 8.2.0 will use the new capnp flist format and lot of commits here are not relevant anymore.

**Pull request closed without merging**
