### PR TITLE
Pass service Object to ActionsBase class during instanciation

### PR DESCRIPTION
**Pull request by zaibon**
currently all the methods from the actions classes of AYS take as first argument a Service object on which the actions.
Since the service object instanciate the actions class, we can directly pass the service object into the actions base class.
This bring less confusion and simplify the interface of the action we implement in the actions class. The service object will always be available, no need to pass it as first argument of each methods.

### CODE REVIEW

**Comment by zaibon** [comment]
@despiegk 
@rkhamis 
any comments on that ?

**Comment by rkhamis** [comment]
I prefer it this way

**Comment by rkhamis** [comment]
Maybe we should rename "serviceObj"  while we're at it?

**Comment by zaibon** [comment]
yep, so just ```service``` ??

**Comment by rkhamis** [comment]
I think that's cleaner, yes

**Pull request merged**
